version: '3.8'

services:
  mongodb:
    image: mongo:8.0
    container_name: social-post-generator-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: social-post-generator
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - social-post-network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  social-post-network:
    driver: bridge
